name: CI
on:
  pull_request:
    branches:
      - main
      - feature/*
  push:
    branches:
      - main

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: install tox
        run: pip install tox

      - name: unit tests
        run: tox --recreate

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ''
          verbose: true